spring:
  profiles:
    active:
      - prod

  datasource:
    url: jdbc:postgresql://localhost:15432/coopvotedb
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true

server:
  servlet:
    context-path: /api

---

spring:
  profiles: prod

  datasource:
    url: ${JDBC_DATASOURCE_URL}

  jpa:
    show-sql: true
    generate-ddl: true

server:
  servlet:
    context-path: /api